<a href="https://colab.research.google.com/github/saksham7143/FeelFinder-NLP-Based-Emotion-Classification-System/blob/main/Emotion_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep= ';', header= None,names= ["text",'emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull()

        text  emotion
0      False    False
1      False    False
2      False    False
3      False    False
4      False    False
...      ...      ...
15995  False    False
15996  False    False
15997  False    False
15998  False    False
15999  False    False

[16000 rows x 2 columns]

In [5]:
df.value_counts().sum()

np.int64(16000)

In [6]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [8]:
emotion_map = {
    'sadness': 1,
    'anger': 2,
    'love': 3,
    'surprise': 4,
    'fear': 5,
    'joy': 6
}

df['emotion'] = df['emotion'].map(emotion_map)

In [9]:
df['text'] = df['text'].apply(lambda x : x.lower())
df

                                                    text  emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        6
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]

In [10]:
def remove_number(txt):
    new = ""

    for i in txt:
        if not i.isdigit():
            new = new + i

    return new

df['text'] = df['text'].apply(remove_number)
df

                                                    text  emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        6
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]

In [11]:
def remove_emoji(txt):
    new = ""

    for i in txt:
        if i.isascii():
            new = new + i

    return new

df["text"] = df["text"].apply(remove_emoji)

df

                                                    text  emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        6
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]

In [12]:
df.loc[2]

text       im grabbing a minute to post i feel greedy wrong
emotion                                                   2
Name: 2, dtype: object

In [13]:
df

                                                    text  emotion
0                                i didnt feel humiliated        1
1      i can go from feeling so hopeless to so damned...        1
2       im grabbing a minute to post i feel greedy wrong        2
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        2
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        1
15996  i am now turning and i feel pathetic that i am...        1
15997                     i feel strong and good overall        6
15998  i feel like this was such a rude comment and i...        2
15999  i know a lot but i feel so stupid because i ca...        1

[16000 rows x 2 columns]

In [14]:
import nltk

In [15]:
from nltk.corpus import stopwords

In [16]:
from nltk.tokenize import word_tokenize

In [17]:
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [18]:
stop_word = set(stopwords.words('english'))

In [19]:
stop_word

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [20]:
def remove_stopwords(txt):
    words = txt.split()
    new = []

    for word in words:
        if word.lower() not in stop_word:
            new.append(word)

    return " ".join(new)

In [21]:
df["text"] = df["text"].apply(remove_stopwords)

In [22]:
df

                                                    text  emotion
0                                  didnt feel humiliated        1
1      go feeling hopeless damned hopeful around some...        1
2              im grabbing minute post feel greedy wrong        2
3      ever feeling nostalgic fireplace know still pr...        3
4                                        feeling grouchy        2
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        1
15996  turning feel pathetic still waiting tables sub...        1
15997                           feel strong good overall        6
15998                     feel like rude comment im glad        2
15999                       know lot feel stupid portray        1

[16000 rows x 2 columns]

In [23]:
X = df.drop("emotion",axis = 1)
y = df['emotion']

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [26]:
X_vector = CountVectorizer()

In [27]:
X_train_bow = X_vector.fit_transform(X_train["text"])
X_test_bow = X_vector.transform(X_test["text"])

In [28]:
from sklearn.naive_bayes import MultinomialNB

m_NB = MultinomialNB()

In [29]:
m_NB.fit(X_train_bow,y_train)

MultinomialNB()

In [30]:
y_pred = m_NB.predict(X_test_bow)

In [31]:
from sklearn.metrics import accuracy_score,classification_report

acc = accuracy_score(y_test,y_pred)
acc

0.768125

In [32]:
from sklearn.linear_model import LogisticRegression

le = LogisticRegression()

In [33]:
le.fit(X_train_bow,y_train)

LogisticRegression()

In [34]:
y_le_pred = le.predict(X_test_bow)

In [35]:
accsc = accuracy_score(y_test,y_le_pred)

In [36]:
print(accsc)
print(classification_report(y_test,y_le_pred))

0.8896875
              precision    recall  f1-score   support

           1       0.93      0.93      0.93       946
           2       0.89      0.86      0.87       427
           3       0.85      0.76      0.80       296
           4       0.86      0.73      0.79       113
           5       0.86      0.84      0.85       397
           6       0.88      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200

# LogisticRegression model is perform better in this DataSet

In [37]:
tfidf = TfidfVectorizer()

In [38]:
X_train_tfidf = tfidf.fit_transform(X_train["text"])
X_test_tfidf = tfidf.transform(X_test["text"])

In [39]:
le.fit(X_train_tfidf,y_train)

LogisticRegression()

In [40]:
y_prep = le.predict(X_test_tfidf)

In [44]:
acc = accuracy_score(y_test,y_prep)
acc

0.8628125

In [47]:
print(classification_report(y_test,y_prep))

              precision    recall  f1-score   support

           1       0.90      0.94      0.92       946
           2       0.90      0.81      0.86       427
           3       0.90      0.61      0.73       296
           4       0.88      0.47      0.61       113
           5       0.86      0.76      0.81       397
           6       0.81      0.96      0.88      1021

    accuracy                           0.86      3200
   macro avg       0.88      0.76      0.80      3200
weighted avg       0.87      0.86      0.86      3200

In [49]:
import joblib

In [52]:
joblib.dump(le,"LogisticRegression_model.pkl")
joblib.dump(X_vector,"count_vectorizer.pkl")

['count_vectorizer.pkl']